slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Ceres Solver Parameters
    ceres_solver_options:
      num_threads: 2  # Set this based on available cores

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: radar_0/scan
    use_map_saver: true
    mode: mapping

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02 #if 0 never publishes odometry
    map_update_interval: 1.0
    resolution: 0.1  # Adjusted for lower-resolution radar data
    max_laser_range: 15.0  # Slightly increased to handle sparse radar data
    minimum_time_interval: 0.5
    transform_timeout: 10.0  #was 0.3 Slightly increased to allow for processing delays
    tf_buffer_duration: 300.
    stack_size_to_use: 2000000
    enable_interactive_mode: false

    # General Parameters
    use_scan_matching: false #use local odometry only
    use_scan_barycenter: false
    minimum_travel_distance: 0.15  # Slightly increased to avoid excessive updates
    minimum_travel_heading: 0.15
    scan_buffer_size: 5  # scan matching disabled
    scan_buffer_maximum_scan_distance: 12.0 
    link_match_minimum_response_fine: 0.08 #ignored since scan matching disabled
    link_scan_maximum_distance: 2.0  #ignored since scan matching disabled
    loop_search_maximum_distance: 5.0  # Increased to allow larger loop closure detections
    do_loop_closing: true
    loop_match_minimum_chain_size: 8  # Reduced to account for sparse features
    loop_match_maximum_variance_coarse: 5.0  # Increased to tolerate radar noise
    loop_match_minimum_response_coarse: 0.3  # Slightly relaxed to improve detection
    loop_match_minimum_response_fine: 0.4  # Slightly relaxed to improve matching

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.7  # Slightly increased to handle uncertainty
    correlation_search_space_resolution: 0.02
    correlation_search_space_smear_deviation: 0.15

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 5.0  # Increased for more robust loop closure
    loop_search_space_resolution: 0.1
    loop_search_space_smear_deviation: 0.05

    # Scan Matcher Parameters
    distance_variance_penalty: 0.3  # Reduced to tolerate radar noise
    angle_variance_penalty: 0.8  # Reduced to be less strict on rotations

    fine_search_angle_offset: 0.005
    coarse_search_angle_offset: 0.4
    coarse_angle_resolution: 0.04
    minimum_angle_penalty: 0.8
    minimum_distance_penalty: 0.4
    use_response_expansion: true